pa = int(input("Prisionero A -> 1) Lo acusas 2) Callas: "))
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
print("...")
pb = int(input("Prisionero A -> 1) Lo acusas 2) Callas: "))

if pa == 1:
    print("Prisionero A lo acusa")
else:
    print("Prisionero A calla")

if pb == 1:
    print("Prisionero B lo acusa")
else:
    print("Prisionero B calla")

if pa == 1 and pb == 1:
    print("5 para A y 5 para B")
elif pa == 1 and pb == 2:
    print("0 para A y 7 para B")
elif pa == 2 and pb == 1:
    print("7 para A y 0 para B")
elif pa == 2 and pb == 2:
    print("2 para A y 2 para B")


