DEUDA_TOTAL = 10000

PROBABILIDAD_EVENTO = 0.1

PORCENTAJE_APUESTA_TACANO = 25
BONIFICACION_TACANO = 50

BONIFICACION_SUERTE_CASUAL = 3

MULTIPLICADOR_BONIFICACION_BEBEDOR = 2

EGO_GANAR = 2
CARISMA_GANAR = 3
FRUSTRACION_GANAR = 2

FRUSTRACION_PERDER = 3
CONFIANZA_PERDER =  1

MIN_ENERGIA_BEBESTIBLE = 2
MAX_ENERGIA_BEBESTIBLE = 8

DINERO_SHOW = 135
ENERGIA_SHOW = 15
FRUSTRACION_SHOW = 12

SHOW_ACTUAL = "La Aventura del Hombre DCC en el Mundo Exterior"